In [3]:
import numpy as np

<font size=6>Numpy notes

<font size=5>1. Creating Arrays/Matrix/Vectors using Numpy

In [49]:
##
print("---Numpy array---")
mlist=[1,2,3]
print(mlist)
print(type(mlist))
nplist=np.array(mlist)
print(nplist)
print(type(nplist))

vect=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(vect)
print(type(vect))

##
print("\n---Zeroes Matrix---")
npzero=np.zeros(3)
print(npzero)
npzero2=np.zeros((2,5))
print(npzero2)
##
print("\n---Ones Matrix---")
npone=np.ones((2,5))
print(npone)
##
print("\n---identity Matrix---")
npid=np.eye(3)
print(npid)

---Numpy array---
[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>

---Zeroes Matrix---
[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

---Ones Matrix---
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

---identity Matrix---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<font size=5>2. Matrix with random numbers

In [84]:
##
npseed=np.random.seed(42) #only lets you generate a particular set of random numbers
##
print("---Matrix with random values---")
nprnd=np.random.rand(3,2)
print(nprnd)
##negative
nprndn=np.random.randn(6)
print("\n negativ",nprndn)
##integers
nprndin=np.random.randint(100) ## generates a random integer upto the given no. 
print("\n int",nprndin)
##
nprndin=np.random.randint(2,10,5) ## generates 5 random integers (here) between the given no.s 2 & 100 
print("\n int2",nprndin)
nprndin=np.random.randint(2,10,(2,3)) ## generates 5 random integers (here) between the given no.s 2 & 100 
print("\n int3",nprndin) ## generates matrix with random integers between the given no.s 2 & 10, and given size 2x3
##

##
print("\n---array created by Numpy---")
nplist2=np.arange(0,10)
print(nplist2)
npvect=np.arange(0,10)
##
print("\n---Reshape matrix---")
npvect2=np.arange(0,10).reshape(2,5)
print(npvect2)
##
print("\n---Numpy generated numbers - 2---")
nplist3=np.linspace(0,10,6)
print(nplist3)
print("linspace generates equally distant numeric elements in an array. However unlike arange, instead of giving the distance/step i 3rd attribute,\nwe provide how many numbers we want in the array. Also by default it also includes the last value in the array which arange() doesn't")
##


---Matrix with random values---
[[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]

 negativ [ 1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769 -0.46572975]

 int 75

 int2 [3 7 6 5 2]

 int3 [[2 4 4]
 [8 3 9]]

---array created by Numpy---
[0 1 2 3 4 5 6 7 8 9]

---Numpy generated numbers - 2---
[ 0.  2.  4.  6.  8. 10.]
linspace generates equally distant numeric elements in an array. However unlike arange, instead of giving the distance/step i 3rd attribute,
we provide how many numbers we want in the array. Also by default it also includes the last value in the array which arange() doesn't

---Reshape matrix---
[[0 1 2 3 4]
 [5 6 7 8 9]]


<font size=5>3. Matrix Properties

In [104]:
##
print("---Max, Min---")
nprand=np.random.randint(5,20,5)
print(nprand)
print("min=",nprand.min())
print("max=",nprand.max())

##index of max and min
print("min index=",nprand.argmin())
print("max index=",nprand.argmax())

##type
print("---type---")
print(nprand.dtype)

##length
print("---length---")
len(nprand)

---Max, Min---
[17 19 17  5 13]
min= 5
max= 19
min index= 3
max index= 1
int32


5